# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aggfuncs.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='aggfuncs.proto',
  package='proto',
  syntax='proto3',
  serialized_options=b'Z\tproto/agg',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0e\x61ggfuncs.proto\x12\x05proto\"7\n\x15InputArgsOfBinaryFunc\x12\x0e\n\x06value1\x18\x01 \x01(\x05\x12\x0e\n\x06value2\x18\x02 \x01(\x05\"\x1c\n\x0bReturnValue\x12\r\n\x05value\x18\x01 \x01(\x05\x32\x87\x01\n\x0egRPCRouteFuncs\x12\x37\n\x03sum\x12\x1c.proto.InputArgsOfBinaryFunc\x1a\x12.proto.ReturnValue\x12<\n\x08multiply\x12\x1c.proto.InputArgsOfBinaryFunc\x1a\x12.proto.ReturnValueB\x0bZ\tproto/aggb\x06proto3'
)




_INPUTARGSOFBINARYFUNC = _descriptor.Descriptor(
  name='InputArgsOfBinaryFunc',
  full_name='proto.InputArgsOfBinaryFunc',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value1', full_name='proto.InputArgsOfBinaryFunc.value1', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value2', full_name='proto.InputArgsOfBinaryFunc.value2', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=80,
)


_RETURNVALUE = _descriptor.Descriptor(
  name='ReturnValue',
  full_name='proto.ReturnValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='proto.ReturnValue.value', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=110,
)

DESCRIPTOR.message_types_by_name['InputArgsOfBinaryFunc'] = _INPUTARGSOFBINARYFUNC
DESCRIPTOR.message_types_by_name['ReturnValue'] = _RETURNVALUE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InputArgsOfBinaryFunc = _reflection.GeneratedProtocolMessageType('InputArgsOfBinaryFunc', (_message.Message,), {
  'DESCRIPTOR' : _INPUTARGSOFBINARYFUNC,
  '__module__' : 'aggfuncs_pb2'
  # @@protoc_insertion_point(class_scope:proto.InputArgsOfBinaryFunc)
  })
_sym_db.RegisterMessage(InputArgsOfBinaryFunc)

ReturnValue = _reflection.GeneratedProtocolMessageType('ReturnValue', (_message.Message,), {
  'DESCRIPTOR' : _RETURNVALUE,
  '__module__' : 'aggfuncs_pb2'
  # @@protoc_insertion_point(class_scope:proto.ReturnValue)
  })
_sym_db.RegisterMessage(ReturnValue)


DESCRIPTOR._options = None

_GRPCROUTEFUNCS = _descriptor.ServiceDescriptor(
  name='gRPCRouteFuncs',
  full_name='proto.gRPCRouteFuncs',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=113,
  serialized_end=248,
  methods=[
  _descriptor.MethodDescriptor(
    name='sum',
    full_name='proto.gRPCRouteFuncs.sum',
    index=0,
    containing_service=None,
    input_type=_INPUTARGSOFBINARYFUNC,
    output_type=_RETURNVALUE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='multiply',
    full_name='proto.gRPCRouteFuncs.multiply',
    index=1,
    containing_service=None,
    input_type=_INPUTARGSOFBINARYFUNC,
    output_type=_RETURNVALUE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GRPCROUTEFUNCS)

DESCRIPTOR.services_by_name['gRPCRouteFuncs'] = _GRPCROUTEFUNCS

# @@protoc_insertion_point(module_scope)
