// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package agg

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GRPCRouteFuncsClient is the client API for GRPCRouteFuncs service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GRPCRouteFuncsClient interface {
	Sum(ctx context.Context, in *InputArgsOfBinaryFunc, opts ...grpc.CallOption) (*ReturnValue, error)
	Multiply(ctx context.Context, in *InputArgsOfBinaryFunc, opts ...grpc.CallOption) (*ReturnValue, error)
}

type gRPCRouteFuncsClient struct {
	cc grpc.ClientConnInterface
}

func NewGRPCRouteFuncsClient(cc grpc.ClientConnInterface) GRPCRouteFuncsClient {
	return &gRPCRouteFuncsClient{cc}
}

func (c *gRPCRouteFuncsClient) Sum(ctx context.Context, in *InputArgsOfBinaryFunc, opts ...grpc.CallOption) (*ReturnValue, error) {
	out := new(ReturnValue)
	err := c.cc.Invoke(ctx, "/proto.gRPCRouteFuncs/sum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gRPCRouteFuncsClient) Multiply(ctx context.Context, in *InputArgsOfBinaryFunc, opts ...grpc.CallOption) (*ReturnValue, error) {
	out := new(ReturnValue)
	err := c.cc.Invoke(ctx, "/proto.gRPCRouteFuncs/multiply", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GRPCRouteFuncsServer is the server API for GRPCRouteFuncs service.
// All implementations must embed UnimplementedGRPCRouteFuncsServer
// for forward compatibility
type GRPCRouteFuncsServer interface {
	Sum(context.Context, *InputArgsOfBinaryFunc) (*ReturnValue, error)
	Multiply(context.Context, *InputArgsOfBinaryFunc) (*ReturnValue, error)
	mustEmbedUnimplementedGRPCRouteFuncsServer()
}

// UnimplementedGRPCRouteFuncsServer must be embedded to have forward compatible implementations.
type UnimplementedGRPCRouteFuncsServer struct {
}

func (UnimplementedGRPCRouteFuncsServer) Sum(context.Context, *InputArgsOfBinaryFunc) (*ReturnValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sum not implemented")
}
func (UnimplementedGRPCRouteFuncsServer) Multiply(context.Context, *InputArgsOfBinaryFunc) (*ReturnValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Multiply not implemented")
}
func (UnimplementedGRPCRouteFuncsServer) mustEmbedUnimplementedGRPCRouteFuncsServer() {}

// UnsafeGRPCRouteFuncsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GRPCRouteFuncsServer will
// result in compilation errors.
type UnsafeGRPCRouteFuncsServer interface {
	mustEmbedUnimplementedGRPCRouteFuncsServer()
}

func RegisterGRPCRouteFuncsServer(s grpc.ServiceRegistrar, srv GRPCRouteFuncsServer) {
	s.RegisterService(&GRPCRouteFuncs_ServiceDesc, srv)
}

func _GRPCRouteFuncs_Sum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InputArgsOfBinaryFunc)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GRPCRouteFuncsServer).Sum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.gRPCRouteFuncs/sum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GRPCRouteFuncsServer).Sum(ctx, req.(*InputArgsOfBinaryFunc))
	}
	return interceptor(ctx, in, info, handler)
}

func _GRPCRouteFuncs_Multiply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InputArgsOfBinaryFunc)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GRPCRouteFuncsServer).Multiply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.gRPCRouteFuncs/multiply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GRPCRouteFuncsServer).Multiply(ctx, req.(*InputArgsOfBinaryFunc))
	}
	return interceptor(ctx, in, info, handler)
}

// GRPCRouteFuncs_ServiceDesc is the grpc.ServiceDesc for GRPCRouteFuncs service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GRPCRouteFuncs_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.gRPCRouteFuncs",
	HandlerType: (*GRPCRouteFuncsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "sum",
			Handler:    _GRPCRouteFuncs_Sum_Handler,
		},
		{
			MethodName: "multiply",
			Handler:    _GRPCRouteFuncs_Multiply_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server-script/aggfuncs/aggfuncs.proto",
}
