// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: server-script/sumfuncs/sumfuncs.proto

package agg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SumArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value1 int32 `protobuf:"varint,1,opt,name=value1,proto3" json:"value1,omitempty"`
	Value2 int32 `protobuf:"varint,2,opt,name=value2,proto3" json:"value2,omitempty"`
}

func (x *SumArgs) Reset() {
	*x = SumArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_script_sumfuncs_sumfuncs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SumArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SumArgs) ProtoMessage() {}

func (x *SumArgs) ProtoReflect() protoreflect.Message {
	mi := &file_server_script_sumfuncs_sumfuncs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SumArgs.ProtoReflect.Descriptor instead.
func (*SumArgs) Descriptor() ([]byte, []int) {
	return file_server_script_sumfuncs_sumfuncs_proto_rawDescGZIP(), []int{0}
}

func (x *SumArgs) GetValue1() int32 {
	if x != nil {
		return x.Value1
	}
	return 0
}

func (x *SumArgs) GetValue2() int32 {
	if x != nil {
		return x.Value2
	}
	return 0
}

type SumReturns struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int32 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *SumReturns) Reset() {
	*x = SumReturns{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_script_sumfuncs_sumfuncs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SumReturns) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SumReturns) ProtoMessage() {}

func (x *SumReturns) ProtoReflect() protoreflect.Message {
	mi := &file_server_script_sumfuncs_sumfuncs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SumReturns.ProtoReflect.Descriptor instead.
func (*SumReturns) Descriptor() ([]byte, []int) {
	return file_server_script_sumfuncs_sumfuncs_proto_rawDescGZIP(), []int{1}
}

func (x *SumReturns) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_server_script_sumfuncs_sumfuncs_proto protoreflect.FileDescriptor

var file_server_script_sumfuncs_sumfuncs_proto_rawDesc = []byte{
	0x0a, 0x25, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2d, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x2f,
	0x73, 0x75, 0x6d, 0x66, 0x75, 0x6e, 0x63, 0x73, 0x2f, 0x73, 0x75, 0x6d, 0x66, 0x75, 0x6e, 0x63,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x39,
	0x0a, 0x07, 0x53, 0x75, 0x6d, 0x41, 0x72, 0x67, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x31, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x32, 0x22, 0x22, 0x0a, 0x0a, 0x53, 0x75, 0x6d,
	0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x32, 0x39, 0x0a,
	0x0d, 0x67, 0x52, 0x50, 0x43, 0x46, 0x75, 0x6e, 0x63, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x28,
	0x0a, 0x03, 0x73, 0x75, 0x6d, 0x12, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x75,
	0x6d, 0x41, 0x72, 0x67, 0x73, 0x1a, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x75,
	0x6d, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x73, 0x42, 0x0b, 0x5a, 0x09, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x61, 0x67, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_server_script_sumfuncs_sumfuncs_proto_rawDescOnce sync.Once
	file_server_script_sumfuncs_sumfuncs_proto_rawDescData = file_server_script_sumfuncs_sumfuncs_proto_rawDesc
)

func file_server_script_sumfuncs_sumfuncs_proto_rawDescGZIP() []byte {
	file_server_script_sumfuncs_sumfuncs_proto_rawDescOnce.Do(func() {
		file_server_script_sumfuncs_sumfuncs_proto_rawDescData = protoimpl.X.CompressGZIP(file_server_script_sumfuncs_sumfuncs_proto_rawDescData)
	})
	return file_server_script_sumfuncs_sumfuncs_proto_rawDescData
}

var file_server_script_sumfuncs_sumfuncs_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_server_script_sumfuncs_sumfuncs_proto_goTypes = []interface{}{
	(*SumArgs)(nil),    // 0: proto.SumArgs
	(*SumReturns)(nil), // 1: proto.SumReturns
}
var file_server_script_sumfuncs_sumfuncs_proto_depIdxs = []int32{
	0, // 0: proto.gRPCFuncsList.sum:input_type -> proto.SumArgs
	1, // 1: proto.gRPCFuncsList.sum:output_type -> proto.SumReturns
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_server_script_sumfuncs_sumfuncs_proto_init() }
func file_server_script_sumfuncs_sumfuncs_proto_init() {
	if File_server_script_sumfuncs_sumfuncs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_server_script_sumfuncs_sumfuncs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SumArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_script_sumfuncs_sumfuncs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SumReturns); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_server_script_sumfuncs_sumfuncs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_script_sumfuncs_sumfuncs_proto_goTypes,
		DependencyIndexes: file_server_script_sumfuncs_sumfuncs_proto_depIdxs,
		MessageInfos:      file_server_script_sumfuncs_sumfuncs_proto_msgTypes,
	}.Build()
	File_server_script_sumfuncs_sumfuncs_proto = out.File
	file_server_script_sumfuncs_sumfuncs_proto_rawDesc = nil
	file_server_script_sumfuncs_sumfuncs_proto_goTypes = nil
	file_server_script_sumfuncs_sumfuncs_proto_depIdxs = nil
}
